name: First CI/CD

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - master
       
jobs:
   ci:
     runs-on: ubuntu-latest
     
     steps:
     - uses: actions/checkout@v2
      
   cd:
     runs-on: ubuntu-latest
     needs: ci

     steps:
      - uses: actions/checkout@v2
      - name: build
        run:  docker build . --file Dockerfile -t ${{ github.repository }} 
      - name: Docker login
        run:  docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        run: |
            docker tag ${{ github.repository }}:latest afielologisele/work_on_git_dock:latest
            docker push afielologisele/work_on_git_dock:latest
